### ISSUE TITLE
Valid plots not found

### ISSUE THREAD

**Issue by GuidoBartoli** [Spare-Network/spare-blockchain#10]
Hi to everybody,
I just installed the Spare GUI on Linux Mint 20 following the [official guide](https://github.com/Spare-Network/spare-blockchain#ubuntudebian). Everything went fine, I successfully imported my private key used to create the plots and the blockchain correctly synced.

However, when I added my folders containing final plots, all of them are listed as "not found" inside Plots tab, so I am not able to farm. I checked on the official Chia GUI and they are all valid, so I think it is something wrong inside the Spare GUI.

Does anyone have this problem? Any suggestion?

Thanks

**Comment by Namsoyo** [comment]
mayby wrong mounted your files?

**Comment by GuidoBartoli** [comment]
They are on a remote shared folder and I thought that was the problem, i.e. accessing files via SMB protocol, but I physically attached the remote disk on the machine farming spares and the problem is still present, so I think it is caused by something else... additionally, I actually can see the list with all the plots inside the GUI, so they can successfully be found, but they are not accepted.
![58A78717-4DFB-4D03-BAF0-D0CEA00FDDE4](https://user-images.githubusercontent.com/16103676/122648977-db6bb500-d12b-11eb-97ba-db60204974f3.jpg)

**Comment by GuidoBartoli** [comment]
I managed to restart the GUI some times and finally it approved my plots, so I think that this issue is somewhat solved.
