### ISSUE TITLE
Windows installer link is not accessible

### ISSUE THREAD

**Issue by Hedonay** [Spare-Network/spare-blockchain#10]
If I click on a link to download Windows client, I get access denied error from Amazon.

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>NJWF1HNYVZT42Y61</RequestId>
<HostId>MDWFdMTEMSS7iu5Vx+moHO6gKMXdGDRZJu0LQnuSfG7hhsubI1PdrBpng3kkSpM2vdZwMjbea+I=</HostId>
</Error>
```

Can someone solve this please? Put it on some other platform to be downloaded from or something?

**Comment by ArIulzZz** [comment]
There's no installer .. it's a zip file .

**Comment by Fishface247** [comment]
im having the same problem with the windows version its not a file but a link

**Comment by Hedonay** [comment]
Right click actually work... and open in new window... ;)

**Comment by Fishface247** [comment]
thanks man
