### ISSUE TITLE
Running spare and silicon at same time issue?

### ISSUE THREAD

**Issue by PC101guy** [Spare-Network/spare-blockchain#102]
It appears that silicon and spare both use the same ports and I can't get one to work when the other is farming, im on windows 10.  anyone know a fix for this? thanks!

**Comment by dfunked** [comment]
Run them on separate machines. VMs are ideal for this kind of thing.

**Comment by PC101guy** [comment]
> 
> 
> Run them on separate machines. VMs are ideal for this kind of thing.

Thanks, I may end up doing this in the future, however I changed some ports in the config and its working now both.

**Comment by stefanel96** [comment]
> > Run them on separate machines. VMs are ideal for this kind of thing.
> 
> Thanks, I may end up doing this in the future, however I changed some ports in the config and its working now both.

Hello, can you tell me which lines specificly did you change, since I can't run chia client and spare in the same time, because both wallets are using port 9265?

**Comment by PC101guy** [comment]
> 
> 
> > > Run them on separate machines. VMs are ideal for this kind of thing.
> > 
> > 
> > Thanks, I may end up doing this in the future, however I changed some ports in the config and its working now both.
> 
> Hello, can you tell me which lines specificly did you change, since I can't run chia client and spare in the same time, because both wallets are using port 9265?

- This is about silicoin and spare not chia and spare, however silicoin was just updated to version 0.0.5 that fixed the port issue.   as far as I know chia does not use port 9265 but 8444 unless im mistaken.

**Comment by stefanel96** [comment]
> > > > Run them on separate machines. VMs are ideal for this kind of thing.
> > > 
> > > 
> > > Thanks, I may end up doing this in the future, however I changed some ports in the config and its working now both.
> > 
> > 
> > Hello, can you tell me which lines specificly did you change, since I can't run chia client and spare in the same time, because both wallets are using port 9265?
> 
> * This is about silicoin and spare not chia and spare, however silicoin was just updated to version 0.0.5 that fixed the port issue.   as far as I know chia does not use port 9265 but 8444 unless im mistaken.

Chias wallet uses 9265, and that actually is the only issue. However, if I change the port of spare or chia wallet to any other number, it still gives me the same connection error but with that new number.

**Comment by root-spare** [comment]
Hi @PC101guy
please feel free to modify config values to use with Spare.

our config file is located at `~/.spare-blockchain/mainnet/config/config.yaml`
