### ISSUE TITLE
having lots of connection and syncing will stop after awhile[BUG]

### ISSUE THREAD

**Issue by jacklwm90** [Spare-Network/spare-blockchain#111]
Hi, I have issue with my node stop syncing and hanged after awhile and I have to restart the GUI in order for it to resync. But this keeps repeating and I am unable to farm properly. I also realized the on my full node tab that I have a lot of connection (over 20) connected. Is this normal?

**Comment by Ratchanida** [comment]
I have the same exact issues. It is frustrating to keep restart a computer every 4 hours to fix the syncing problem.   Is there a Spare Blockchain software update? I am currently using version 1.1.7137

**Comment by jacklwm90** [comment]
solved the problem by editing target_peer_count in the config file from 800 to 80. now syncing without issue and program did not hang. will monitor for a few days and update/close the issue.

**Comment by dknalca** [comment]
> solved the problem by editing target_peer_count in the config file from 800 to 80. now syncing without issue and program did not hang. will monitor for a few days and update/close the issue.

Where is the config file in windows? C:\Users\userXXX\.spare-blockchain\mainnet\config

I have the same issue...
