### ISSUE TITLE
Introducer after last update

### ISSUE THREAD

**Issue by sanok2000** [Spare-Network/spare-blockchain#21]
full_node full_node_server        : INFO     Cannot connect to host introducer.sparecoin.org:9444 ssl:<ssl.SSLContext object at 0x10cd15e40> [nodename nor servname provided, or not known]

**Comment by thauch** [comment]
same issue. not syncing

**Comment by siddtharth** [comment]
same issue as well.

**Comment by neuro1978** [comment]
Anche a me non sincronizza proprio
