### ISSUE TITLE
No logs after updating to 0.1.dev5

### ISSUE THREAD

**Issue by DrShotsPHD** [Spare-Network/spare-blockchain#22]
After updating to 0.1.dev5 no logs are being written to debug.log

**Comment by chrnueve** [comment]
config folder changed from .sparecoin to **.spare-coin**. Check if your **.spare-coin/mainnet/config/config.yaml** has log_level to INFO

**Comment by root-spare** [comment]
please check .spare-blockchain , we moved our config files to new location

**Comment by DrShotsPHD** [comment]
@root-spare thanks!
