### ISSUE TITLE
Connecting to wallet

### ISSUE THREAD

**Issue by Lexeres** [Spare-Network/spare-blockchain#30]
![изображение](https://user-images.githubusercontent.com/79547625/122685622-43e29100-d215-11eb-8851-070f26877325.png)

**Comment by Lexeres** [comment]
working on the latest version

**Comment by Asger7879** [comment]
> working on the latest version

just downloaded 1 minute ago and it doesn't work
![1](https://user-images.githubusercontent.com/86205366/122686365-3e874580-d219-11eb-97df-72c2ed248417.png)
