### ISSUE TITLE
Unable to create New Wallet

### ISSUE THREAD

**Issue by ThighHoney** [Spare-Network/spare-blockchain#31]
![image](https://user-images.githubusercontent.com/86205066/122685791-9b640b00-d1db-11eb-816c-5a9a7d2a6b1c.png)

I got passed the "Connecting to Wallet" issue but now I am stuck on the above

**Comment by morgado198028** [comment]
what did you do to start the wallet

**Comment by root-spare** [comment]
@ThighHoney please specify you OS

**Comment by morgado198028** [comment]
the os is Windows
Whallet dont even start

**Comment by ThighHoney** [comment]
Apologies, I downloaded the SSL certs and moved them into the appropriate folder. I ran the application as admin.
OS is windows 10

**Comment by ThighHoney** [comment]
After about 30 min I am in bit like everyone else it will not sync and I cant attach plots. This feels very unfinished but I will leave it open to see what happens.
