### ISSUE TITLE
does it work for someone?

### ISSUE THREAD

**Issue by MocaFer** [Spare-Network/spare-blockchain#32]
does not synchronize, does not recognize most of the plots. I ran it through all operational systems with no luck.
Is it me or is it them?

**Comment by nickmaklife** [comment]
me too

**Comment by katzenhai2** [comment]
With the latest windows update (downloaded now) the difficulty was set to 7 (again). I'm syncing now but all nodes (13 atm) are at height 0. :))
All my plots are recognized.

**Comment by nickmaklife** [comment]
> With the latest windows update (downloaded now) the difficulty was set to 7 (again). I'm syncing now but all nodes (13 atm) are at height 0. :))
> All my plots are recognized.

me too

**Comment by MocaFer** [comment]
![IMG_0078](https://user-images.githubusercontent.com/86169581/122686121-f3a00a80-d1e5-11eb-8dfd-a15cc35f820b.jpeg)
- [ ]

**Comment by lksgriep** [comment]
downloaded last version and still doesnt work.

**Comment by katzenhai2** [comment]
> 
> 
> ![IMG_0078](https://user-images.githubusercontent.com/86169581/122686121-f3a00a80-d1e5-11eb-8dfd-a15cc35f820b.jpeg)
> 
>     * [ ]

Sent us some IPs from your nodes with height > 1,000

**Comment by the-vibe-dev** [comment]
They changed the certs again no old ips will work.

**Comment by MocaFer** [comment]
what needs to be done to make it work?
Will there be delete nodes?

**Comment by katzenhai2** [comment]
Now it works... I'm farming at height 0. :))
No proofs found yet. We will see. 43 TiB of plots. No sync because everyone is stucked at height 0. I set the debug log to INFO and can see many people haven't updated because their nodes are rejected because of wrong SSL.

**Comment by MocaFer** [comment]
So it's just just time for me to finally sync?

**Comment by katzenhai2** [comment]
> 
> 
> So it's just just time for me to finally sync?

If you have the final build downloaded/updated: It looks promoising now. Wait. Have a look for challenges at "Farm".

**Comment by katzenhai2** [comment]
Reminds me of chia:

"2 plots were eligible for farming xxxxxx **Found 0 proofs**. Time: 0.50044 s."

**Comment by MocaFer** [comment]
![IMG_0079](https://user-images.githubusercontent.com/86169581/122686695-fd773d00-d1e8-11eb-805d-c67e59183ec3.jpeg)

**Comment by katzenhai2** [comment]
![spare1](https://user-images.githubusercontent.com/86201425/122686770-4b089f80-d213-11eb-8dc5-c2e7528d2d3d.jpg)

![spare2](https://user-images.githubusercontent.com/86201425/122686810-8acf8700-d213-11eb-9813-e9192c4d311a.jpg)


Feels like being the first farming at Chia. lol
Hopefully I'm not ghost-farming. hahaha

**Comment by MocaFer** [comment]
Yeahhhhhh

**Comment by djjaeger82** [comment]
Was synced and farming, now back to syncing 0/1293 again

**Comment by katzenhai2** [comment]
> 
> 
> Was synced and farming, now back to syncing 0/1293 again

You should be at height 0 or something above. The 1293 seems to be some old nodes before the last build (update).

**Comment by djjaeger82** [comment]
> You should be at height 0 or something above. The 1293 seems to be some old nodes before the last build (update). They have changed the SSL certificates and the difficulty.

I thought new certs would prevent us from connecting to them, apparently not.  Manually deleted the 1293 person from the connection list.  now back to not synced.

**Comment by katzenhai2** [comment]
Wow, we are now at height 1. :)) Seems I was really one of the first guys in spare. Mega loool
Though haven't found any proofs yet. :((

Update: Height 2. Woohoooo!
Update: Estimated time to win: 3 hours. Okay... need to wait. :D

**Comment by MocaFer** [comment]
we all really hate you so badly, lol

**Comment by dfunked** [comment]
Last height farmed: 1

Haha, I did it!!!

**Comment by Namsoyo** [comment]
It works now great.

just update your client

**Comment by djjaeger82** [comment]
yep working now :)

**Comment by MocaFer** [comment]
EVERYTHING IS WORKING: YEAAAAAAAAA !!!!!!!!!
