### ISSUE TITLE
Not Synced

### ISSUE THREAD

**Issue by Voroshok** [Spare-Network/spare-blockchain#4]
20 minutes synced is 0, why?

**Comment by walruzperil** [comment]
Same here

**Comment by qiuqiu1104** [comment]
Same here

**Comment by ryu007za** [comment]
Same, zero sync :( I have open my port too

**Comment by Namsoyo** [comment]
i am on peak height 27575 but stcuk allways for minutes
an i got some full nodes with 0 ore 127
![image](https://user-images.githubusercontent.com/86157618/122680874-c8231d00-d1f1-11eb-81bf-455fe6cd53b1.png)
but i get on setup allways same warnings

**Comment by katolla** [comment]
seeing lots of nodes with 27527 blocks, and lots with 127 blocks, i guess the full reset of the chain did not work

**Comment by ZAD-Blackminers** [comment]
same problem here ... 0/27,575 synced

**Comment by renriquemh28** [comment]
> same problem here ... 0/27,575 synced

At least you have 0/27575 my just said not synced

**Comment by katolla** [comment]
i assume old and new clients on the same network causing chaos. the port has not even changed, for a full reset i did expect the port to change or an other herd way to break compatibility with the old chain to prevent chaos between new and old chain. well, no clue but anyways this was fail nr 2 i think, waiting for 3 because three times is the charm

**Comment by renriquemh28** [comment]
anybody has the full note ip? that maybe help to synced

**Comment by katolla** [comment]
it seems to jump between old and new chain, sometimes i see a sync with a peak height 162, then again it jumps to not synced / syncing 162 / 27625, then again to synced with 162. farming starts but difficulty 1, way to low again, many proofs but no reward.

**Comment by Namsoyo** [comment]
who got 27xxx please go offline and update your client

**Comment by katolla** [comment]
just updated to the latest github version and now its not even starting to sync

**Comment by djjaeger82** [comment]
Same here, latest git hub still not syncing, stuck at peak height 662.  Also, difficulty still set to 1.... wasn't it supposed to be 7 for the relaunch?

**Comment by katolla** [comment]
same here still stuck at 662

**Comment by grayfallstown** [comment]
grayfallstown ChiaPlotStatus Dev — heute um 20:25 Uhr
./spare show -a 84.106.177.34:9444
./spare show -a [2a02:2f0b:820e:c100:5b3d:fcb3:d32b:8d1b]:9444
./spare show -a [2804:d59:9a44:a600:29b1:c5ec:7ce0:d1f]:9444
./spare show -a [2001:569:7c08:cb00:71ce:45d8:c84:39b6]:9444
./spare show -a [2a02:2f0b:820e:c100:a44f:19e1:664a:457b]:9444
./spare show -a 2a02:2f0b:820e:c100:5b3d:fcb3:d32b:8d1b:9444
./spare show -a 78.48.26.22:9444
./spare show -a 2804:d59:9a44:a600:29b1:c5ec:7ce0:d1f:9444
./spare show -a 2001:569:7c08:cb00:71ce:45d8:c84:39b6:9444
./spare show -a 65.92.146.253:9444
./spare show -a 182.138.227.245:9444
./spare show -a 2a02:2f0b:820e:c100:a44f:19e1:664a:457b:9444
./spare show -a 117.136.38.67:9444
./spare show -a 77.21.195.137:9444
./spare show -a 54.185.14.61:9444
./spare show -a 31.172.141.220:9444
./spare show -a 92.96.108.28:9444

**Comment by katolla** [comment]
no matter what node i try to connect to connecting from your list, it fails
spare show -a 65.92.146.253:9444,
Connecting to 65.92.146.253, 9444,
Failed to connect to 65.92.146.253:9444,

results in stuck at 662

**Comment by SergeyGorbunov** [comment]
Anybody can show nodes with height more 662?

**Comment by katolla** [comment]
i assume grey just did, but with my updated client i cant connect to any of them, already tried to delete everything and started over again with a fresh copy from git, deleted my database files, all config files, killed all spare processes... stuck  662 and not even seeing a node in the list with an other height

**Comment by grayfallstown** [comment]
1060 with the peers I pasted before.
Delete your .sparecoin/mainnet/db and resync with those peers

**Comment by katolla** [comment]
> 1060 with the peers I pasted before.
> Delete your .sparecoin/mainnet/db and resync with those peers

i already did, no change. i see you have a different directory then me, for me it is ".spare-coin/mainnet/db/" so i assume you did not update to the latest github version

i assume everyone who updated 1h ago is stuck at 662 and everyone who just starts with that version

**Comment by grayfallstown** [comment]
> i assume you did not update to the latest github version

Running latest windows build

**Comment by djjaeger82** [comment]
> > i assume you did not update to the latest github version
> 
> Running latest windows build

latest windows build is behind github repository and out of date...

**Comment by grayfallstown** [comment]
> latest windows build is behind github repository and out of date...

@root-spare can we get a windows update?

**Comment by Voroshok** [comment]
Thats OK with New version.

**Comment by Admin-Miner** [comment]
Hello ! my windows version i downloaded is not syncing. what can i do now ?

**Comment by andreipdev** [comment]
I had not syncing on Windows, turned off the software, opened it again, and now it's Syncing. Well it still says 0/4213 as of this writing but hopefully it will now work.

Edit: Fully synched now.

**Comment by DiabloROY** [comment]
I cannot sync either due to the "introducer.sparecoin.org" (IP 54.193.4.225) not responding to ping (request time out). Therefore, the client can't be getting nodes from the network.
