### ISSUE TITLE
Proofs in log files

### ISSUE THREAD

**Issue by the-vibe-dev** [Spare-Network/spare-blockchain#43]
I am not seeing attempted proofs in log files. I have changed log level to INFO. Any suggestions?

**Comment by ryu007za** [comment]
firstly did you restart the application after changing log level?

**Comment by the-vibe-dev** [comment]
I did. I am seeing INFO level log entries just none that show attempted proofs or eligible plots.

**Comment by the-vibe-dev** [comment]
I restarted harvester and I am getting proofs now.
