### ISSUE TITLE
how to recover farmed reward?

### ISSUE THREAD

**Issue by tiny0little** [Spare-Network/spare-blockchain#55]
after so many restarts, how to recover farmed rewards?
I still have old blockchain and wallet DB as a proof

**Comment by feliperiosm** [comment]
I have the same question.... best regards

**Comment by dfunked** [comment]
They've relaunched the blockchain... Any blocks that you won previously won't be valid any more. No choice but to move on and forget about them.

Kind of frustrating that they didn't do this via testnet instead before launching properly on mainnet, but it is what it is...

**Comment by tiny0little** [comment]
not acording to this twit

![image](https://user-images.githubusercontent.com/25114540/122746124-5f3fb180-d292-11eb-84ae-8392f5618b7c.png)

**Comment by digitalfreddy** [comment]
I'm in the same situation. Does anyone have more information?

**Comment by tiny0little** [comment]
i received the rewards. thx!
