### ISSUE TITLE
Wallet port conflict with chia_wallet

### ISSUE THREAD

**Issue by cdgraff** [Spare-Network/spare-blockchain#6]
(venv) chia@chia1:/opt/spare-blockchain$ spare farm summary
Connection error. Check if wallet is running at 9256

That is the default CHIA_wallet port, I thinks was missing update into config.

I have updated manually the port into config to avoid this issues.

**Comment by denisio** [comment]
I confirm

**Comment by root-spare** [comment]
Thank you , @cdgraff, @denisio  ! this issue is now resolved
