### ISSUE TITLE
Windows client stops syncing after a while

### ISSUE THREAD

**Issue by WiseGuyNL** [Spare-Network/spare-blockchain#70]
Everything seems to work great but after a while, the client just stops farming/syncing.
A restart of the client gets things going again, no errors are displayed.

Any thoughts?

**Comment by SergeyKGoncharov** [comment]
Make sure you have the latest version of the app installed? Even if the last one is installed, reinstall it again. The developers made corrections without public notice and without changing the release number. Perhaps this is your problem
![image](https://user-images.githubusercontent.com/84588771/122887653-c8cec700-d349-11eb-9890-1e8073d03492.png)

**Comment by WiseGuyNL** [comment]
> Make sure you have the latest version of the app installed? Even if the last one is installed, reinstall it again. The developers made corrections without public notice and without changing the release number. Perhaps this is your problem
> ![image](https://user-images.githubusercontent.com/84588771/122887653-c8cec700-d349-11eb-9890-1e8073d03492.png)

Yes, that is the one I'm using, which seems to be the lastest version.

**Comment by Borissensei** [comment]
Same here

**Comment by Dman3105** [comment]
Same issue, could be after 5 minutes or as much as a few hours. Status will say farming and synced but the challenges stop moving requiring a application restart. Have to babysit the application to ensure it is working.

**Comment by prophetz2021** [comment]
same here, both peak height and last attemped proof stop after sometime. need to restart app to resync again

**Comment by Koi-1** [comment]
Same here. The error start with:
OSError: [Errno 10048] error while attempting to bind on address ('::1', 9256, 0, 0): solo se permite un uso de cada direcci󮠤e socket (protocolo/direcci󮠤e red/puerto).
I checked it and this port "9256" is the rpc_port. 

After that, start news errors:
Traceback (most recent call last):
  File "spare\rpc\rpc_server.py", line 281, in connect_to_daemon
  File "spare\rpc\rpc_server.py", line 239, in connection
  File "aiohttp\client_ws.py", line 230, in receive
  File "aiohttp\streams.py", line 644, in read
  File "aiohttp\streams.py", line 604, in read

I believe that error is when it try to open a new connection between ports 9256, but the system can not close the previous session.

**Comment by SergeyKGoncharov** [comment]
same here. need to restart app to resync again

**Comment by cmundaca79** [comment]
I have this error and the program stop.

2021-06-22T14:30:49.310 full_node full_node_server        : WARNING  Cannot write to closing transport 5.66.36.92
2021-06-22T14:34:49.070 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '115.195.98.112', 'port': 9444}. Traceback (most recent call last):
  File "spare\server\server.py", line 536, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

**Comment by Threadgodripper** [comment]
Same here, need to restart after hours

**Comment by urufusaru** [comment]
Same here. after running for some hours, it stop syncing.

**Comment by Iridexx** [comment]
Same here!!!!!!!

**Comment by Dman3105** [comment]
Seems to be happening quicker and quicker. Having to go on every few minutes and restart the app if I want to keen Farming.

**Comment by SergeyKGoncharov** [comment]
Yes, it used to work for about an hour, but now it needs to be restarted every 10 minutes. I can't even imagine how many coins all users have lost due to the unstable operation of the Windows application

**Comment by Fishface247** [comment]
I've now noticed that wallet is only showing syncing not synced after having the same problems as everyone else in this thread.

**Comment by cmundaca79** [comment]
I found this indication in Discord:

purfus — Yesterday at 8:00 AM
In the config.yaml file target_outbound_peer_count must be changed to 8 and target_peer_count to 80, this is the setting from the original 1.1.7 Chia code.  The Spare default is way too many node connections for an average computer.  It causes the node to fail connections but still shows a synced status.

Original 
  target_outbound_peer_count: 80
  target_peer_count: 800

Recommend
  target_outbound_peer_count: 8
  target_peer_count: 80

I used this configuration and apparently it works. I used a different value for target_peer_count (40).

**Comment by WiseGuyNL** [comment]
> I found this indication in Discord:
> 
> purfus — Yesterday at 8:00 AM
> In the config.yaml file target_outbound_peer_count must be changed to 8 and target_peer_count to 80, this is the setting from the original 1.1.7 Chia code. The Spare default is way too many node connections for an average computer. It causes the node to fail connections but still shows a synced status.
> 
> Original
> target_outbound_peer_count: 80
> target_peer_count: 800
> 
> Recommend
> target_outbound_peer_count: 8
> target_peer_count: 80
> 
> I used this configuration and apparently it works. I used a different value for target_peer_count (40).

Is this the file? :
\resources\app.asar.unpacked\daemon\spare\util\initial-config.yaml

**Comment by cmundaca79** [comment]
In this path:   C:\Users\myuser\\.spare-blockchain\mainnet\config

**Comment by WiseGuyNL** [comment]
> In this path: C:\Users\myuser\.spare-blockchain\mainnet\config

Thanks, I'd already found it :)
It's been running for a while now, so far so good! I'll check back in a few hours

**Comment by WiseGuyNL** [comment]
Thanks, this was the issue!
Client has been running all night without a problem
