### ISSUE TITLE
Farmer stoped

### ISSUE THREAD

**Issue by Hatt3rPi** [Spare-Network/spare-blockchain#75]
Many times a day I must force the application to close since it stops farming and the GUI does not indicate any error indications.
![image](https://user-images.githubusercontent.com/11076084/123031474-53e3a780-d3b2-11eb-9c78-c8b93ac6ffcb.jpeg)
![image](https://user-images.githubusercontent.com/11076084/123031483-580fc500-d3b2-11eb-9613-25667fb5cbe3.jpeg)

**Comment by LimakKAAM** [comment]
Hi, I also found out this morning. The application frozen after one day! Peak frozen 22.6 18:22 and stoped synced.  I have to restart and then working.

**Comment by Hatt3rPi** [comment]
Yep, same problem in this hour
 ![image](https://user-images.githubusercontent.com/11076084/123034714-08cc9300-d3b8-11eb-882c-e7892e79ce6b.jpeg)

**Comment by Fishface247** [comment]
Same here

**Comment by Dman3105** [comment]
Same, sometimes within a few minutes.

**Comment by LimakKAAM** [comment]
And again. This is very bad.

**Comment by LimakKAAM** [comment]
Again the same problem! a few minutes back.

**Comment by SergeyKGoncharov** [comment]
Same here. Developers do not respond to the problem and do not respect users

**Comment by mrcustodio** [comment]
SOLUTION BY DISCORD USER --> lowestofttim

In the config.yaml file target_outbound_peer_count must be changed to 8 and target_peer_count to 80, this is the setting from the original 1.1.7 Chia code.  The Spare default is way too many node connections for an average computer.  It causes the node to fail connections but still shows a synced status. Spare has it set to 80 and 800.

**Comment by Hatt3rPi** [comment]
> SOLUTION BY DISCORD USER --> lowestofttim
> 
> 
> 
> In the config.yaml file target_outbound_peer_count must be changed to 8 and target_peer_count to 80, this is the setting from the original 1.1.7 Chia code.  The Spare default is way too many node connections for an average computer.  It causes the node to fail connections but still shows a synced status. Spare has it set to 80 and 800.

Its work! Thx
