### ISSUE TITLE
The transaction is not working and the wallet is not syncing

### ISSUE THREAD

**Issue by Asger7879** [Spare-Network/spare-blockchain#76]
I decided to create a wallet and make a trial transfer, as a result, nothing was transferred and the wallet synchronization does not occur, but the node synchronization is successful.

![image](https://user-images.githubusercontent.com/86205366/123046727-1f4d0b80-d405-11eb-915a-6f5a4efa3f7d.png)
![image](https://user-images.githubusercontent.com/86205366/123046742-2542ec80-d405-11eb-9ead-58f348baea3e.png)
![image](https://user-images.githubusercontent.com/86205366/123047104-91bdeb80-d405-11eb-96bc-3e1a1097d011.png)

Screenshot of the transfer from the main wallet:
![image](https://user-images.githubusercontent.com/86205366/123046966-63401080-d405-11eb-84e3-f61c104fe120.png)

**Comment by Fishface247** [comment]
my wallet is also showing syncing
