### ISSUE TITLE
on Windows = wallet connections 0 but wallet sync. why connections wallet 0?

### ISSUE THREAD

**Issue by eksperTR** [Spare-Network/spare-blockchain#80]
![wallet](https://user-images.githubusercontent.com/86369479/123128992-44b53600-d454-11eb-8ca8-4afe41d637b0.jpg)

**Comment by urufusaru** [comment]
I have the same, but not Synced

**Comment by jeanfrodrigues** [comment]
click on menu KEYS, then click on ur key, and u should be reconnect!

**Comment by eksperTR** [comment]
> 
> 
> click on menu KEYS, then click on ur key, and u should be reconnect!

thanks. Now wallet ok.

**Comment by urufusaru** [comment]
In my case, there were mutiple instances of "start_wallet.exe" still running in task manager. It seems that when the GUI stops working there are some exe's still running after I closed the program.

**Comment by jeanfrodrigues** [comment]
> In my case, there were mutiple instances of "start_wallet.exe" still running in task manager. It seems that when the GUI stops working there are some exe's still running after I closed the program.

its normal i think, the chia's program do that too when u close!

**Comment by eksperTR** [comment]
> 
> 
> In my case, there were mutiple instances of "start_wallet.exe" still running in task manager. It seems that when the GUI stops working there are some exe's still running after I closed the program.

pc reset
