### ISSUE TITLE
Farming on many machines???

### ISSUE THREAD

**Issue by alex826-pex** [Spare-Network/spare-blockchain#83]
How to harvest on other machines that are not your main machine???

**Comment by dfunked** [comment]
It's based on Chia, so same exact principal as the "farming on many machines" page from their Wiki

**Comment by alex826-pex** [comment]
Does the port number need to be changed?  Is the command exactly the same? chia start harvester  ? Thx

**Comment by dfunked** [comment]
You seem to be asking this on all of the forked coins... It'll be the same steps for each. Look at the config.yaml file on your main node and  you should be able to identify which port the farmer uses, but you shouldn't need to change anything there.

Copy the CA folder from the full node to the harvester, edit config.yaml on that and put in the IP of your full node and then init + start harvester.
In this case you would do "spare init" followed by "spare start harvester"
