### ISSUE TITLE
loose Full Node Connection

### ISSUE THREAD

**Issue by olgyan93btc** [Spare-Network/spare-blockchain#86]
Hi, After about 30 minutes, the full node connection is lost and as a result, the processing of the plots stops. only restarting the computer can help. See picture.
![loose connection](https://user-images.githubusercontent.com/83642938/123277212-e6c83300-d4d3-11eb-81b8-53a91a9069db.jpg)

**Comment by olgyan93btc** [comment]
in Windows 10

**Comment by olgyan93btc** [comment]
In the config.yaml file target_outbound_peer_count must be changed to 8 and target_peer_count to 80, this is the setting from the original 1.1.7 Chia code. The Spare default is way too many node connections for an average computer. It causes the node to fail connections but still shows a synced status.

Original
target_outbound_peer_count: 80
target_peer_count: 800

Recommend
target_outbound_peer_count: 8
target_peer_count: 80

**Comment by khalid077** [comment]
how to open and modify it sir?
please help as im a newbie
im using windows I have found the config.yaml file of spare but dont know what to do

**Comment by omjanu** [comment]
What are the full hash connections. I am not getting any of them.

**Comment by olgyan93btc** [comment]
C:\Users\user name\.spare-blockchain\mainnet\config.yaml
open with Notepad and change 

Original
target_outbound_peer_count: 80
target_peer_count: 800

Change to 
target_outbound_peer_count: 8
target_peer_count: 80
