### ISSUE TITLE
How to fix error 22

### ISSUE THREAD

**Issue by KaninWi** [Spare-Network/spare-blockchain#89]
[Error 22] File not found. Most likely one of the plot folders in your config.yaml has an issue.

**Comment by vivianhipolito** [comment]
sim certo mais como faco para arrumar?

**Comment by olgyan93btc** [comment]
You need to replace the config file 
C:\Users\HDD 001\.spare-blockchain\mainnet\config\config.yaml

**Comment by root-spare** [comment]
@KaninWi  is this issue still valid for you?
