### ISSUE TITLE
Not found Plots

### ISSUE THREAD

**Issue by xiaoluodayan** [Spare-Network/spare-blockchain#95]
![image](https://user-images.githubusercontent.com/10309043/123781892-52146980-d907-11eb-8e79-e3483356dbb6.png)

**Comment by rones-dev** [comment]
I have the same issue - around 500 plots none is detected ??? !!!

**Comment by igli94** [comment]
Same issue also for me ive entered the blockchain with my chia mnemonic im  still getting plot non found error. Any idea how to fix these guys? Tried installing unistalling the app still haven’t helped. How can i make a clean install? Where does the spare app saves it’s files o  windows?

**Comment by olgyan93btc** [comment]
You need to replace one file.
C:\Users\xxxxxxx\.spare-blockchain\mainnet\config\config.yaml

**Comment by root-spare** [comment]
@xiaoluodayan, @rones-dev , @olgyan93btc @igli94  please make sure that you have added your Chia plotting key so that Spare GUI client will be able to use plots plotted with that key.

Thank you !
