### ISSUE TITLE
The DNS query name does not exist: dns-introducer-spare.sparecoin.org.

### ISSUE THREAD

**Issue by msdogra** [Spare-Network/spare-blockchain#96]
Looks like dns-introducer-spare.sparecoin.org is gone....

**Comment by pnobrega80** [comment]
Yep. Gone. Can't connect

**Comment by jfikar** [comment]
someone has list of working nodes, please? `spare show -c`

**Comment by root-spare** [comment]
this issue has been resolved, thank you for your patience a lot! @msdogra , @pnobrega80 , @jfikar
